import type { Metadata, Viewport } from 'next'

import { Inter_Tight, Geist_Mono, Instrument_Serif } from 'next/font/google'
import './globals.css'

import { Toaster } from '@/components/ui/sonner'
import { ReactQueryClientProvider } from '@/components/others/query-client-provider'

const interTight = Inter_Tight({ variable: '--font-inter-tight', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })
const instrumentSerif = Instrument_Serif({ variable: '--font-instrument-serif', weight: ['400'], style: ['italic'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Starter Kit',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ReactQueryClientProvider>
      <html lang='en' suppressHydrationWarning>
        <head>
          <meta name='theme-color' content='#ffffff' />
          <meta name='apple-mobile-web-app-status-bar-style' content='black-translucent' />
        </head>
        <body className={`${interTight.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased bg-background`}>
          {children}
          <Toaster position='top-center' richColors />
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}

